name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: build with gradle
      run: |
        echo "开始进行release构建"
        chmod +x gradlew
        ./gradlew app:assembleRelease
    - name : upload apk
      uses: actions/upload-artifact@master
      if: always()
      with:
        name: rstp_apk
        path: ${{ github.workspace }}/app/build/outputs/apk/release
